[build-system]
requires = ["setuptools>=60.0",
            "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nodo"
version = "0.1.0"
dependencies = []

[project.scripts]
nodo = "nodo.main:main"